curl -X POST http://localhost:8085/addnode \
     -H "Content-Type: application/json" \
     -d '{
           "parent_key": "0",
           "subject": "New Subject",
           "title": "New Title",
           "value": "Some Value"
         }'
